services:
  klaps-frontend:
    container_name: klaps-frontend-${ENV_SUFFIX:-prod}
    image: ghcr.io/biplo12/klatka:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
