services:
  klaps-frontend:
    container_name: klaps-frontend-${ENV_SUFFIX:-prod}
    image: ghcr.io/biplo12/klaps:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.klaps-frontend-${ENV_SUFFIX:-prod}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.klaps-frontend-${ENV_SUFFIX:-prod}.entrypoints=websecure"
      - "traefik.http.routers.klaps-frontend-${ENV_SUFFIX:-prod}.tls.certresolver=leresolver"
      - "traefik.http.services.klaps-frontend-${ENV_SUFFIX:-prod}.loadbalancer.server.port=3000"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
